export enum Dimension {
  // HomeWin = 'H',
  // AwayWin = 'A',
  // Draw = 'D'
  CanvasMinHeight = 300,
  CanvasMinWidth = 300,
  MarginX = 30,
  MarginY = 30,
  CanvasPaddingX = 30,
  CanvasPaddingY = 30,
  FramePaddingX = 10,
  FramePaddingY = 10,
  FrameMarginX = 10,
  FrameMarginY = 10,
  FnWidth = 30,
  FnHeight = 30,
  DataUnitWidth = 40,
  DataUnitHeight = 40,
  // DataMarginX = 40,
  // DataUnitHeight = 40,
  TextPaddingX = 10,
  TextPaddingY = 10,
  TextWidth = 30,
  TextHeight = 30,
  FontFamily = 'Arial',
  FontSize = 12,
  FontStyle = 'normal',
  FontVariant = 'normal'
}
/// shift to layout?
