export enum Dimension {
  CanvasMinHeight = 300,
  CanvasMinWidth = 300,
  CanvasPaddingX = 30,
  CanvasPaddingY = 30,
  LevelPaddingX = 10,
  LevelPaddingY = 10,
  FramePaddingX = 10,
  FramePaddingY = 10,
  FrameMarginX = 10,
  FrameMarginY = 10,
  FnWidth = 30,
  FnHeight = 30,
  DataUnitWidth = 40,
  DataUnitHeight = 40,
  TextPaddingX = 10,
  TextPaddingY = 10,
  TextMinWidth = 30,
  FontFamily = 'Arial',
  FontSize = 15,
  FontStyle = 'normal',
  FontVariant = 'normal'
}
